version: '2'

services:
  postgres:
    build: ./compose/docker-postgis
    volumes:
      - /mnt/volume-sfo2-01/odaa/db:/var/lib/postgresql
      - /mnt/volume-sfo2-01/odaa/backups:/backups
    environment:
      - ALLOW_IP_RANGE=172.18.0.0/16


  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gis
      - USE_DOCKER=yes
    volumes:
      - .:/app
      - /mnt/volume-sfo2-01/odaa:/data      
    expose:
      - "8000"
    links:
      - postgres
    
  rstudio:
    build: ./compose/rstudio
    volumes:
      - .:/home
      - /mnt/volume-sfo2-01/odaa:/data
    env_file: rstudio.env
    expose:
      - "8787"
    links:
      - postgres

  mapserver:
    build: ./compose/c2c_mapserver
    volumes:
      - /mnt/volume-sfo2-01/odaa:/data
    expose:
      - "80"
    links:
      - postgres
      
  mapcache:
    build: ./compose/mapcache
    volumes:
      - /mnt/volume-sfo2-01/odaa:/data
    expose:
      - "80"
    links:
      - mapserver    
    depends_on:
      - mapserver

  nginx:
    build: 
      context: ./compose/nginx
      dockerfile: Dockerfile-dev
    depends_on:
      - django
      - rstudio
      - certbot
      - mapcache

    ports:
      - "0.0.0.0:80:80"

    environment:
      - MY_DOMAIN_NAME=webmap.positionbot.com
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: quay.io/letsencrypt/letsencrypt
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d webmap.positionbot.com  --text --agree-tos --email info@geoanalytic.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm


